language: erlang

sudo: required

before_install:
  - git clone https://github.com/erlang/rebar3.git; cd rebar3; ./bootstrap; sudo cp rebar3 /usr/bin; cd ..
  - git clone https://github.com/inaka/elvis.git; cd elvis; rebar3 escriptize; sudo cp _build/default/bin/elvis /usr/bin; cd ..

notifications:
  email: false

otp_release:
  - 21.0
  - 20.3
  - 19.3

script:
  - make elvis-rock
  - make edoc
  - make xref
  - make eunit
  - |
    OTP_RELEASE=`erl -noshell -eval 'io:format(erlang:system_info(otp_release)), halt(0)'`
    if [ $OTP_RELEASE -eq 21 ]; then
      make dialyzer
      make cover
      make coveralls
    else
      make cover
    fi

