name: Erlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp-version: [26, 27, 28]

    container:
      image: erlang:${{ matrix.otp-version }}

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: make eunit && make cover
    - name: Run Dialyzer
      run: make dialyzer
